# Generated by Django 5.1.6 on 2025-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='profile_pics/default.jpg', max_length=255),
        ),
    ]
